hello/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('hellodjango.urls')),
    url(r'^showtime/',include('showtime.urls')),
    url(r'^',include('students.urls',namespace='students'))
]

hellodjango/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$',index),
]

showtime/urls.py
from django.conf.urls import url
from .views import current_time

# 这里是应用的url地址,正则匹配如果加上,在url中就得添加
urlpatterns = [
    url(r'^$',current_time),
]

students/urls.py
from django.conf.urls import url

from students.views import student_list,stu_message,index

urlpatterns = [
    url(r'^student_list/$',student_list,name='student_list'),
    url(r'^stu_message/(?P<id>\d+)/$',stu_message,name='stu_message'),
    url(r'^index/$',index,name='index')
]

grades/models.py
from django.db import models

# Create your models here.


# 班级模型类
class Grade(models.Model):
    # 定义字段
    name = models.CharField(max_length=32,verbose_name='班级')
    created_time = models.DateTimeField(verbose_name='创建时间')
    girl_num = models.PositiveIntegerField(verbose_name='女生人数')
    boy_num = models.PositiveIntegerField(verbose_name='男生人数')
    description = models.CharField(max_length=256,verbose_name='描述')
    # 布尔值,判断是否删除
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '班级'

hellodjango/models.py
from django.db import models

# Create your models here.

showtime/models.py
from django.db import models

# Create your models here.

students/models.py
from django.db import models

# Create your models here.


# 定义student模型
from grades.models import Grade


class Student(models.Model):
    name = models.CharField(max_length=32,verbose_name='姓名')
    gender = models.BooleanField(verbose_name='性别')
    age = models.PositiveIntegerField(verbose_name='年龄')
    info = models.CharField(max_length=200,verbose_name='简介')
    is_deleted = models.BooleanField(default=False)
    # 关联外键
    grade = models.ForeignKey(Grade)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '学生'

grades/views.py
from django.shortcuts import render

# Create your views here.

hellodjango/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from datetime import datetime


# 定义视图函数
def index(request):
    return render(request, 'hellodjango/hello.html')
    # return HttpResponse("<h1>你好,django</h1>")

showtime/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
# Create your views here.


def current_time(request):
    now = datetime.now()
    # return HttpResponse("<h1>It is %s</h1>"%now)
    return render(request,'showtime/current_time.html',{'now':now})

students/views.py
from django.shortcuts import render,HttpResponse,redirect

# Create your views here.

# 显示学生信息
from django.urls import reverse

from students.models import Student

# 学生信息展示页
def student_list(request):
    student_list = Student.objects.all()
    return render(request,'students/student.html',locals())
    # return redirect(reverse("students:index"))

# 学生个人信息展示页
def stu_message(request,id):
    # return HttpResponse("你真帅")
    student = Student.objects.get(id=id)
    return render(request,'students/stu_message.html',locals())

# 反向解析的函数
def index(request):
    return render(request,'students/index.html')

hellodjango/templates/hellodjango/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello django</title>
</head>
<body>
    <h1 align="center">hello django</h1>
</body>
</html>

showtime/templates/showtime/current_time.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Show_time</title>
</head>
<body>
    <h1 align="center">It's {{ now }}</h1>
</body>
</html>

students/templates/students/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
    <h1>welcome 董时玉</h1>
</body>
</html>

students/templates/students/stu_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人信息</title>
</head>
<body>
    <h1 align="center">千峰python个人学员信息</h1>
    <hr>
    <P align="center">{{ student.name }}</P>
    <P align="center">{{ student.age }}</P>
    <P align="center">{{ student.gender }}</P>
</body>
</html>

students/templates/students/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生信息</title>
</head>
<body>
    <h1 align="center">千峰python学员信息</h1>
    <hr>
        <table border="1" cellpadding="10" width="800" align="center">
            <tr align="center">
                <td>姓名</td>
                <td>年龄</td>
                <td>性别</td>
                <td>介绍</td>
                <td>班级</td>
            </tr>
            {% for student in student_list %}
                <tr align="center">
                    <td><a href="{% url 'students:stu_message' id=student.id%}">{{ student.name }}</a></td>
                    <td>{{ student.age }}</td>
                    <td>{{ student.gender }}</td>
                    <td>{{ student.info }}</td>
                    <td>{{ student.grade }}</td>
                </tr>
            {% endfor %}
        </table>
</body>
</html>